APP_SECRET_NAME_PREFIX = "GIT_PROVIDER_APP_SECRET"
APP_INSTALL_SECRET_NAME_PREFIX = "GIT_PROVIDER_APP_INSTALL_SECRET"
APP_INSTALL_GAT_NAME_PREFIX = "GIT_PROVIDER_GAT_INSTALL_SECRET"
APP_INSTALL_WAT_NAME_PREFIX = "GIT_PROVIDER_WAT_INSTALL_SECRET"
APP_INSTALL_PAT_NAME_PREFIX = (
    "GIT_PROVIDER_PAT_INSTALL_SECRET"  # Azure DevOps PAT prefix
)
APP_INSTALL_BBDC_HTTP_NAME_PREFIX = "GIT_PROVIDER_BBDC_HTTP_INSTALL_SECRET"  # Bitbucket Data Center HTTP Access Token prefix
