import asyncio
import os
import subprocess
import tempfile
from enum import StrEnum
from pathlib import Path

from aiolimiter import AsyncLimiter
from pydantic import BaseModel
from shared.agent.chat_openai_async import ChatOpenAI, OutputConfig, OutputConfigKind
from shared.inspector.onboarding import (
    azure_devops_ops,
    bitbucket_dc_ops,
    bitbucket_ops,
    gh_ops,
    gitlab_ops,
)
from shared.inspector.utils.git_fetcher_pygit2 import CommitData, GitFetcher
from shared.prompts.structured_prompting import (
    GENERAL_STE_STYLE_INSTRUCTION,
    Component,
    Prompt,
)
from tqdm.asyncio import tqdm_asyncio

MAX_COMMITS_TO_PROCESS = 15000


class CommitType(StrEnum):
    feature = "feature"
    bugfix = "bugfix"
    refactor = "refactor"
    chore = "chore"
    docs = "docs"
    test = "test"
    performance = "performance"
    style = "style"
    build = "build"
    other = "other"


class CommitSummary(BaseModel):
    summary: str
    type: CommitType


OPENAI_SEM = asyncio.Semaphore(75)
OPENAI_LIMITER = AsyncLimiter(25, 1)  # 25 requests per second

commit_summary_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a meticulous software development assistant. Your task is to summarize code changes in a clear and concise way, based on both the commit message and the actual code diff.

    Your summary should:
    - Reflect what the commit **actually does**, not just what the message claims.
    - Include the **type of change** (e.g., feature, bugfix, refactor, test addition, performance improvement).
    - Highlight **key files or functions** modified if they are relevant to understanding the change.
    - Be written in natural language that could be used in a changelog, code review, or documentation.

    Provide the summary in 1 paragraph. Be sure to highlight any major features added, bugs fixed, or significant refactors. If the commit is a minor change or typo fix, note that as well.
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)

commit_summary_user_prompt_template = """
Summarize the following commit. Use both the commit message and the diff to produce a meaningful description of what changed and why.

### Commit Message
{commit_message}

### Diff
{commit_diff}
"""

changelog_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a changelog aggregation assistant.

    You will receive a set of commit summaries generated by another model. Your task is to:

    1. Organize entries under standardized categories:
    - Features - Break down new features into sub-sections that describe the feature with 1-5 bullet points. Include any major refactors here.
    - Bug Fixes - A list of no more than 3-5 important bug fixes.
    - Ignore other types of changes. DO NOT list chores, documentation changes, or testing updates.
    2. **Deduplicate or merge** similar entries (e.g., multiple commits that add a similar feature or fix related issues).
    3. **Clean up language** to be clear, human-readable, and professional. Do not include file paths or commit hashes, describe the features in human readable language. You should reference important code entities as needed though.

    Use a clean Markdown format for the final output, suitable for inclusion in a `CHANGELOG.md` file.

    IMPORTANT INSTRUCTIONS:
    - DO NOT include any commit hashes or file paths in the final output.
    - DO NOT list more than 3-5 bugs in the Bug Fixes section
    - DO NOT describe minor refactors or changes that do not significantly impact the codebase.
    - DO NOT include any personal opinions or subjective language.
    - DO ignore other types of changes like chores, documentation updates, or testing changes.
    - DO summarize features in 1-5 bullet points, focusing on the key aspects of the feature.

    DO NOT summarize or conclude the changelog, just provide the changelog information as is.
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)


class MonthlyChangelog(BaseModel):
    month: str
    changes: list[str]


class OverallChangelog(BaseModel):
    changelog: list[MonthlyChangelog]


overall_changelog_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a structured summarization agent tasked with generating a one-page historical timeline of a software codebase. Your output will be consumed by other LLM-based agents via an MCP server to reason about feature history, architectural shifts, and capability evolution.

    You will read detailed changelogs or release notes and extract high-signal, chronologically ordered entries.

    Your output must:

    - Each entry should describe a month and should contain at most 10 bullet points to capture the most important changes that month.
    - Each bullet should:
        - Begin with a **strong action verb** (e.g., Introduced, Refactored, Migrated)
        - Reference the **feature, subsystem, or outcome**
        - Be **atomic**, avoiding pronouns and vague references
        - Avoid opinion, commentary, or duplication

    Do not include explanation, comments, or any markdown — output only the JSON output.

    An example output format is:
    {"changelog": [
        {"month": "2024-02", "changes": ["Introduced real-time notification system", "Fixed critical authentication bugs"]},
        {"month": "2024-01", "changes": ["Migrated database to PostgreSQL"]}
    ]}
    Be sure to format the date as YYYY-MM and organize months in reverse chronological order (most recent first).

    Capture the most important changes each month, prioritizing features and significant bug fixes over minor changes. Limit each month to no more than 10 bullet points.
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)

merge_changelog_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a changelog merge assistant. You will receive two changelog entries for the same month - an existing/older changelog and a new changelog with recent updates.

    Your task is to intelligently merge these two changelogs by:
    1. **Combining unique entries** from both changelogs
    2. **Deduplicating similar entries** (e.g., if the same feature or bug fix appears in both)
    3. **Preserving the most complete description** when similar entries exist
    4. **Maintaining the standardized format** with Features and Bug Fixes sections
    5. **Prioritizing recent changes** if there are conflicts

    Output merged changelog in Markdown format that represents a comprehensive view of all changes for that month.

    IMPORTANT:
    - DO NOT include commit hashes or file paths
    - DO NOT duplicate information
    - DO maintain professional, clear language
    - DO preserve all unique features and important bug fixes from both changelogs
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)

update_overall_changelog_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a changelog update assistant. You will receive an existing overall changelog (in YAML format) and new monthly changelog entries (in Markdown format).

    Your task is to update the overall changelog by:
    1. **Adding new month entries** that don't exist in the overall changelog
    2. **Updating existing month entries** where new changes have been added
    3. **Preserving the tone** with strong action verbs and atomic bullet points
    4. **Maintaining chronological order** (most recent months first)
    5. **Deduplicating** similar entries between old and new content

    Each bullet point must:
    - Begin with a strong action verb (e.g., Introduced, Refactored, Migrated)
    - Reference the feature, subsystem, or outcome
    - Be atomic and clear, avoiding pronouns and vague references

    Output only valid JSON. No explanation or markdown.

    Example format:
    {"changelog": [
        {"month": "2024-02", "changes": ["Introduced real-time notification system", "Fixed critical authentication bugs"]},
        {"month": "2024-01", "changes": ["Migrated database to PostgreSQL"]}
    ]}
    Be sure to format the date as YYYY-MM.
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)


async def llm_generate(
    llm: ChatOpenAI, system_prompt: str, user_prompt: str, config: OutputConfig
) -> str:
    async with OPENAI_SEM, OPENAI_LIMITER:
        if len(user_prompt) > 250000:
            print("Long user prompt detected, truncating to 250000 characters.")
            user_prompt = user_prompt[:250000]  # Truncate to avoid issues
        return await llm.generate_response(
            system_prompt=system_prompt, user_prompt=user_prompt, output_cfg=config
        )


async def summarize_commits(
    commits: list[CommitData],
) -> dict[str, CommitSummary]:  # {sha: summary}
    llm = ChatOpenAI(model="gpt-4.1", temperature=0.0, request_timeout=120)
    summarized_commits = {}  # {sha: summary}
    sha_list = []
    task_coroutines = []
    for commit in commits:
        sha_list.append(commit.sha)
        user_prompt = commit_summary_user_prompt_template.format(
            commit_message=commit.message, commit_diff=commit.diff
        )
        config = OutputConfig(kind=OutputConfigKind.JSON_STRICT, payload=CommitSummary)
        task_coroutines.append(
            llm_generate(llm, commit_summary_system_prompt, user_prompt, config)
        )
    task_results = await tqdm_asyncio.gather(*task_coroutines)

    for sha, result in zip(sha_list, task_results):
        parsed_response = CommitSummary.parse_raw(result)
        summarized_commits[sha] = parsed_response
    return summarized_commits


async def make_monthly_changelog(
    all_commits: list[CommitData],
    commit_summaries: dict[str, CommitSummary],
) -> dict[str, str]:
    model = ChatOpenAI(
        model="o3-mini",
        temperature=0.0,
        request_timeout=400,
    )

    commit_prompt_by_month = {}

    for commit in all_commits:
        month_key = commit.authored_date.strftime("%Y-%m")
        if month_key not in commit_prompt_by_month:
            commit_prompt_by_month[month_key] = ""

        commit_prompt_by_month[month_key] += (
            f"**{commit.sha}**: {commit_summaries[commit.sha].summary} (Type: {commit_summaries[commit.sha].type})\n\n"
        )

    aggregated_results = {}  # {month_key: str}
    task_coroutines = []
    for month_key, commit_prompt in commit_prompt_by_month.items():
        user_prompt = f"### Commits for {month_key}\n{commit_prompt}"
        config = OutputConfig(
            kind=OutputConfigKind.TEXT,
        )
        task_coroutines.append(
            llm_generate(model, changelog_system_prompt, user_prompt, config)
        )

    aggregated_results = await tqdm_asyncio.gather(*task_coroutines)
    monthly_summaries = {}
    for month_key, result in zip(commit_prompt_by_month.keys(), aggregated_results):
        monthly_summaries[month_key] = result

    return monthly_summaries


async def generate_overall_changelog(
    monthly_changelogs: dict[str, str],
) -> str:
    overall_changelog_model = ChatOpenAI(
        model="gpt-5",
        temperature=0.0,
        request_timeout=600,
    )

    overall_changelog_user_prompt = ""
    for month_key, result in monthly_changelogs.items():
        overall_changelog_user_prompt += f"### Changelog for {month_key}\n{result}\n"

    overall_changelog_config = OutputConfig(
        kind=OutputConfigKind.JSON_STRICT, payload=OverallChangelog
    )
    overall_changelog_result = await llm_generate(
        overall_changelog_model,
        overall_changelog_system_prompt,
        overall_changelog_user_prompt,
        overall_changelog_config,
    )
    changelog_parsed = OverallChangelog.parse_raw(overall_changelog_result)

    overall_changelog_yaml = "changelog:\n"
    for entry in changelog_parsed.changelog:
        overall_changelog_yaml += f"  - {entry.month}:\n"
        for change in entry.changes:
            overall_changelog_yaml += f"      - {change}\n"

    return overall_changelog_yaml


async def merge_monthly_changelogs(
    old_changelog: str,
    new_changelog: str,
    month_key: str,
) -> str:
    merge_model = ChatOpenAI(
        model="gpt-5",
        temperature=0.0,
        request_timeout=120,
    )

    user_prompt = f"""
### Month: {month_key}

### Existing Changelog:
{old_changelog}

### New Changelog Updates:
{new_changelog}

Please merge these two changelogs intelligently, preserving all unique content and deduplicating similar entries.
"""

    config = OutputConfig(kind=OutputConfigKind.TEXT)
    merged_result = await llm_generate(
        merge_model,
        merge_changelog_system_prompt,
        user_prompt,
        config,
    )
    return merged_result


async def update_overall_changelog(
    old_overall_changelog: str,
    new_monthly_changes: dict[str, str],
) -> str:
    update_model = ChatOpenAI(
        model="gpt-5",
        temperature=0.0,
        request_timeout=600,
    )

    new_changes_prompt = ""
    for month_key, changelog in new_monthly_changes.items():
        new_changes_prompt += f"### {month_key}\n{changelog}\n\n"

    user_prompt = f"""
### Existing Overall Changelog (YAML):
{old_overall_changelog}

### New Monthly Changes (Markdown):
{new_changes_prompt}

Please update the overall changelog by intelligently merging these new changes with the existing changelog.
"""

    config = OutputConfig(kind=OutputConfigKind.JSON_STRICT, payload=OverallChangelog)
    updated_changelog = await llm_generate(
        update_model,
        update_overall_changelog_system_prompt,
        user_prompt,
        config,
    )
    updated_changelog_yaml = "changelog:\n"
    changelog_parsed = OverallChangelog.parse_raw(updated_changelog)
    for entry in changelog_parsed.changelog:
        updated_changelog_yaml += f"  - {entry.month}:\n"
        for change in entry.changes:
            updated_changelog_yaml += f"      - {change}\n"
    return updated_changelog_yaml


async def _prepare_repo_for_changelog(
    version_id: str,
    install_id: str,
    temp_dir: str,
) -> tuple[Path, str, str]:
    from database.db import engine
    from database.models import GitProviderAppInstallation
    from database.models_enums import PrimaryAssetProvider
    from shared.inspector.utils.db import (
        get_version_by_id,
        git_provider_app_installation_by_id,
    )
    from sqlmodel import Session, select

    version = await get_version_by_id(version_id)
    repo_id = version.primary_asset.repository_id
    repo_name = version.primary_asset.display_name
    provider = version.primary_asset.provider
    tracked_branch = version.primary_asset.vcs_tracked_branch

    if provider == PrimaryAssetProvider.GITHUB:
        access_token = gh_ops.fetch_app_access_token(install_id)
        clone_url, full_name = gh_ops.get_repo_clone_info_from_id(repo_id, access_token)
    elif provider == PrimaryAssetProvider.BITBUCKET:
        access_token = bitbucket_ops.fetch_access_token(install_id)
        gp_install = git_provider_app_installation_by_id(installation_id=install_id)
        workspace = gp_install.git_provider_app.provider_metadata["workspace"]
        repo_slug = version.primary_asset.display_name
        # Bitbucket allows spaces in repo names, but does not URL encode them
        # and instead replaces them with hyphens.
        # We need to replace spaces with hyphens in the repo name.
        repo_slug = "-".join(repo_name.split())  # multiple spaces go to single hyphen

        clone_url, full_name = bitbucket_ops.get_repo_clone_info_from_id(
            workspace, repo_slug, access_token
        )
    elif provider == PrimaryAssetProvider.GITLAB_SELF_MANAGED:
        with Session(engine) as session:
            installation_id = version.primary_asset.installation_id
            app_install = session.exec(
                select(GitProviderAppInstallation).where(
                    GitProviderAppInstallation.id == installation_id
                )
            ).one()
            if app_install is None:
                raise ValueError(f"Installation ID {installation_id} not found.")
            base_url = app_install.git_provider_app.base_url
        access_token = gitlab_ops.fetch_access_token(install_id)
        clone_url, full_name = gitlab_ops.get_repo_clone_info_from_id(
            base_url, repo_id, access_token
        )
    elif provider == PrimaryAssetProvider.AZURE_DEVOPS_CLOUD:
        with Session(engine) as session:
            installation_id = version.primary_asset.installation_id
            app_install = session.exec(
                select(GitProviderAppInstallation).where(
                    GitProviderAppInstallation.id == installation_id
                )
            ).one()
            if app_install is None:
                raise ValueError(f"Installation ID {installation_id} not found.")
            base_url = app_install.git_provider_app.base_url
            # Extract project from VCS metadata
            vcs_metadata = version.vcs_metadata or {}
            project = (
                vcs_metadata.get("repository", {}).get("namespace", "").split("/")[-1]
            )
            if not project:
                raise ValueError(
                    f"Could not determine project from VCS metadata for version {version_id}"
                )
        access_token = azure_devops_ops.fetch_access_token(install_id)
        clone_url, full_name = azure_devops_ops.get_repo_clone_info_from_id(
            base_url, project, repo_id, access_token
        )
    elif provider == PrimaryAssetProvider.BITBUCKET_DATA_CENTER:
        # Bitbucket DC uses Bearer auth via git http.extraHeader
        # Fetch full secrets for SSL configuration
        # Note: fetch_secrets applies BITBUCKET_DC_INSTANCE_URL env var override if set
        secrets = bitbucket_dc_ops.fetch_secrets(install_id)
        access_token = secrets["token"]
        instance_url = secrets.get("instance_url", "")
        disable_ssl_verify = secrets.get("disable_ssl_verify", False)
        ca_bundle_path = secrets.get("ca_bundle_path")

        vcs_metadata = version.vcs_metadata or {}
        project_key = vcs_metadata.get("project_key", "")
        if not project_key:
            project_key = vcs_metadata.get("repository", {}).get("namespace", "")
        repo_slug = repo_name.lower().replace(" ", "-")
        clone_url, full_name = bitbucket_dc_ops.get_repo_clone_info_from_id(
            instance_url, project_key, repo_slug
        )
    else:
        raise ValueError(f"Unsupported provider: {provider}")

    repo_dir = Path(temp_dir) / full_name

    # Bitbucket DC requires Bearer auth via git http.extraHeader and SSL handling
    if provider == PrimaryAssetProvider.BITBUCKET_DATA_CENTER:
        env = os.environ.copy()
        if disable_ssl_verify:
            env["GIT_SSL_NO_VERIFY"] = "true"
        elif ca_bundle_path:
            env["GIT_SSL_CAINFO"] = ca_bundle_path

        result = subprocess.run(
            [
                "git",
                "-c",
                f"http.extraHeader=Authorization: Bearer {access_token}",
                "clone",
                clone_url,
                str(repo_dir),
            ],
            cwd=None,
            capture_output=True,
            text=True,
            env=env,
        )
    else:
        result = subprocess.run(
            ["git", "clone", clone_url, str(repo_dir)],
            cwd=None,
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        print(f"Git clone failed for {clone_url}: {result.stderr}")
        raise subprocess.CalledProcessError(
            result.returncode, f"git clone {clone_url} {repo_dir}"
        )

    if tracked_branch is not None:
        result = subprocess.run(
            f"git checkout {version.vcs_hash}",
            shell=True,
            cwd=repo_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise subprocess.CalledProcessError(
                result.returncode, f"git checkout {version.vcs_hash}"
            )

    return repo_dir, full_name, version.vcs_hash


async def create_changelog(
    version_id: str,
    install_id: str,
) -> dict:
    with tempfile.TemporaryDirectory() as temp_dir:
        repo_dir, full_name, vcs_hash = await _prepare_repo_for_changelog(
            version_id, install_id, temp_dir
        )

        repo = GitFetcher(repo_path=repo_dir)
        # Fetch commits is CPU-bound work, so run it in a thread.
        commits_ret = await asyncio.to_thread(
            repo.fetch_commits, start_commit=vcs_hash, limit=MAX_COMMITS_TO_PROCESS
        )
        all_commits = list(commits_ret)

        print(f"Fetched {len(all_commits)} commits from {full_name}")
        if not all_commits:
            print("No commits found, skipping changelog generation.")
            return {}

        summarized_commits = await summarize_commits(all_commits)
        monthly_changelogs = await make_monthly_changelog(
            all_commits, summarized_commits
        )
        overall_changelog = await generate_overall_changelog(monthly_changelogs)

        return {
            "monthly_changelogs": monthly_changelogs,
            "overall_changelog": overall_changelog,
        }


async def update_changelog(
    version_id: str,
    install_id: str,
    previous_sha: str,
    previous_monthly_changelogs: dict[str, str],
    previous_overall_changelog: str,
) -> dict:
    with tempfile.TemporaryDirectory() as temp_dir:
        repo_dir, full_name, vcs_hash = await _prepare_repo_for_changelog(
            version_id, install_id, temp_dir
        )

        repo = GitFetcher(repo_path=repo_dir)
        # This list of commits includes new commits that occurred chronologically since previous_sha up to and including vcs_hash,
        # PLUS any commits that are unique ancestors of merge commits contained in the set of new commits
        # that may have occurred chronologically before previous_sha.
        # Fetch commits is CPU-bound work, so run it in a thread.
        commits_ret = await asyncio.to_thread(
            repo.fetch_commits,
            start_commit=vcs_hash,
            limit=MAX_COMMITS_TO_PROCESS,
            stop_commit=previous_sha,
            unravel_merges=True,
        )
        new_commits = list(commits_ret)

        print(f"Fetched {len(new_commits)} commits from {full_name}")
        if not new_commits:
            print("No commits found, skipping changelog generation.")
            return {}

        summarized_commits = await summarize_commits(new_commits)
        new_monthly_changelogs = await make_monthly_changelog(
            new_commits, summarized_commits
        )

        # Merge new monthly changelogs with existing ones
        merged_monthly_changelogs = dict(previous_monthly_changelogs)

        for month_key, new_changelog in new_monthly_changelogs.items():
            if month_key in previous_monthly_changelogs:
                # Month exists in both old and new - merge them
                merged_changelog = await merge_monthly_changelogs(
                    previous_monthly_changelogs[month_key], new_changelog, month_key
                )
                merged_monthly_changelogs[month_key] = merged_changelog
            else:
                # New month not in old changelog - just add it
                merged_monthly_changelogs[month_key] = new_changelog

        # Update overall changelog using LLM to intelligently merge only what's needed
        updated_overall_changelog = await update_overall_changelog(
            previous_overall_changelog, new_monthly_changelogs
        )

        return {
            "monthly_changelogs": merged_monthly_changelogs,
            "overall_changelog": updated_overall_changelog,
        }
